### ISSUE TITLE
Support for Mono/Linux

### ISSUE THREAD

**Issue by mr0mega** [OpenZWave/openzwave-dotnet-uwp#15]
OpenZWave supports Linux, and with mono it's possible to run .Net applications. What steps are needed to make this library Linux compatible?

**Comment by dotMorten** [comment]
Due to the native dependency of this library, it's quite a big task to add support for other platforms. One thing to keep in mind is that this isn't really a .NET Library. This is a C++/CLI  library on Windows and C++/CX library on UWP. These types of C++ libraries just work straight against a .NET component on Windows.

Making this work on Linux would essentially be a complete rewrite of the library by wrapping openzwave in a C-API Library and then write a .NET p/invoke layer on top. This is A LOT of work to build and maintain, and quite error prone, and I personally do not have the resources to undertake such a huge task.
