### ISSUE TITLE
Unmaintained

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/openzwave-dotnet-uwp#42]
This wrapper has not been updated to the latest OZW release and may not work well. If you would like to consider taking over maintanance of this wrapper please contact @dotMorten or myself.

**Comment by dotMorten** [comment]
Sorry. I'm just rather uncomfortable adding the DNS query trick because I don't know how to do that without leaking private information about what devices one is using.  You said it's just a dns query but as those queries usually are not even encrypted, I don't see how that's not 
risking leaking PI. Up until recently OZW worked completely offline.

**Comment by ftballguy45** [comment]
What exactly is this in reference to? I do hope someone soon can took over this project and get it current

**Comment by toby11** [comment]
Can anyone confirm which version of OZW it should work with?

**Comment by dotMorten** [comment]
Sync'ed up with master pending https://github.com/OpenZWave/open-zwave/pull/2550 merged

**Comment by toby11** [comment]
Does this mean the there are now no issues with this wrapper and the current ozw master?

**Comment by dotMorten** [comment]
Works On My Machine™️

**Comment by yesyesuk** [comment]
Does this mean that we will soon be able to use CENTRAL_SCENE with this wrapper? That would be awesome!

**Comment by dotMorten** [comment]
@yesyesuk  Please follow / contribute to: https://github.com/OpenZWave/openzwave-dotnet-uwp/issues/28
